import { useCallback,useEffect,useMemo,useState } from 'react'
import {AlertTriangle,Boxes,CheckCircle2,Database,Download,Fingerprint,GitBranch,PackageCheck,RefreshCw,ScanSearch,ShieldCheck,ShieldX,Workflow} from 'lucide-react'
import {createWaiverV34,evidenceUrlV34,getOverviewV34,revokeWaiverV34,runAssessmentV34,savePolicyV34,type V34Overview} from './lib/supplyChainApiV34'

const short=(v?:string|null)=>v?v.slice(0,12):'—'
const when=(v?:string|null)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('ar-SA')}
const box=(ok=true)=>`rounded-2xl border p-4 ${ok?'border-white/10 bg-white/[0.035]':'border-amber-400/25 bg-amber-500/10'}`
const tone=(v?:boolean|null)=>v===true?'text-emerald-300':v===false?'text-rose-300':'text-amber-300'

export default function VideoStudioV34(){
 const [o,setO]=useState<V34Overview|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[policy,setPolicy]=useState<Record<string,any>>({})
 const [waiver,setWaiver]=useState({code:'',reason:'',hours:24})
 const load=useCallback(async()=>{try{const d=await getOverviewV34();setO(d);setPolicy(d.policy||{});setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل V34.')}},[])
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t)},[load])
 const act=async(name:string,fn:()=>Promise<any>,ok:string)=>{setBusy(name);setError('');setMessage('');try{await fn();setMessage(ok);await load()}catch(e){setError(e instanceof Error?e.message:`فشلت ${name}`)}finally{setBusy('')}}
 const release=o?.activeRelease,assessment=o?.latestAssessment,gate=o?.productionGate,py=assessment?.pythonLock||{},wf=assessment?.workflow||{},gh=assessment?.githubAttestation||{},v33=gate?.v33||assessment?.v33||{}
 const flags=useMemo(()=>[
  ['requirePythonHashLock','Require Python SHA-256 transitive lock'],['requireTorchCpuPins','Require protected Torch CPU stack'],['requireCrossRunnerReproducible','Require Ubuntu 22/24 reproducibility'],['requireSyftArtifactSbom','Require Syft artifact SBOM'],['requireArtifactScanner','Require Trivy artifact scan'],['requireCriticalScanGate','Require CRITICAL scan gate'],['requireGithubOidcStep','Require GitHub OIDC provenance step'],['requireGithubAttestationApi','Require GitHub Attestations API proof'],['requireV33ProductionGate','Require V33 production gate'],['requirePostgresForProduction','Require PostgreSQL evidence store'],['allowTemporaryWaivers','Allow temporary waivers']],[])
 if(!o)return <main className="min-h-screen bg-[#050911] p-8 text-slate-100" dir="rtl"><div className="mx-auto max-w-xl rounded-3xl border border-white/10 bg-white/5 p-8 text-center"><Workflow className="mx-auto mb-4 h-10 w-10 animate-pulse text-cyan-300"/><h1 className="text-xl font-black">Creator V34 Hermetic Build</h1><p className="mt-2 text-sm text-slate-400">{error||'جاري تحميل الأدلة...'}</p></div></main>
 return <main className="min-h-screen bg-[#050911] text-slate-100" dir="rtl">
  <header className="border-b border-white/10 bg-[#070d17]/95 px-5 py-4"><div className="mx-auto flex max-w-[1850px] flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[11px] font-black tracking-[.15em] text-cyan-300"><ShieldCheck className="h-4 w-4"/> HERMETIC · CROSS-RUN · SYFT · TRIVY · OIDC · WAIVERS</div><h1 className="mt-1 text-2xl font-black">MAGHRABI Video Studio · Creator V34</h1><p className="mt-1 text-xs text-slate-500">Full Hermetic Build & Artifact Verification</p></div><div className="flex gap-2"><a href="#video-v33" className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">V33</a><a href="#video-v32" className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">V32</a><button onClick={()=>void load()} className="flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2 text-xs font-black text-slate-950"><RefreshCw className="h-4 w-4"/>REFRESH</button></div></div></header>
  <div className="mx-auto max-w-[1850px] space-y-5 p-5">
   {(error||message)&&<div className={`rounded-2xl border p-3 text-sm ${error?'border-rose-400/30 bg-rose-500/10 text-rose-200':'border-emerald-400/30 bg-emerald-500/10 text-emerald-200'}`}>{error||message}</div>}
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-8">
    <div className={box(o.schema.databaseMode==='postgresql')}><Database className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">EVIDENCE DB</div><b>{o.schema.databaseMode.toUpperCase()}</b></div>
    <div className={box(Boolean(release))}><GitBranch className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">CANDIDATE</div><b className="font-mono">{short(release?.candidateSha)}</b></div>
    <div className={box(Boolean(py.hashComplete))}><PackageCheck className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">PY HASH LOCK</div><b className={tone(assessment?Boolean(py.hashComplete):null)}>{assessment?(py.hashComplete?'LOCKED':'BLOCK'):'ASSESS'}</b></div>
    <div className={box(Boolean(wf.crossRunner))}><Workflow className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">CROSS-RUN</div><b className={tone(assessment?Boolean(wf.crossRunner):null)}>{assessment?(wf.crossRunner?'MATCH':'UNKNOWN'):'ASSESS'}</b></div>
    <div className={box(Boolean(wf.syft))}><Boxes className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">SYFT SBOM</div><b className={tone(assessment?Boolean(wf.syft):null)}>{assessment?(wf.syft?'PASS':'UNKNOWN'):'ASSESS'}</b></div>
    <div className={box(Boolean(wf.criticalGate))}><ScanSearch className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">TRIVY CRITICAL</div><b className={tone(assessment?Boolean(wf.criticalGate):null)}>{assessment?(wf.criticalGate?'PASS':'BLOCK'):'ASSESS'}</b></div>
    <div className={box(Boolean(wf.oidc))}><Fingerprint className="mb-2 h-5 w-5 text-cyan-300"/><div className="text-[10px] text-slate-500">OIDC PROVENANCE</div><b className={tone(assessment?Boolean(wf.oidc):null)}>{assessment?(wf.oidc?'PASS':'UNKNOWN'):'ASSESS'}</b></div>
    <div className={box(Boolean(gate?.ready))}>{gate?.ready?<CheckCircle2 className="mb-2 h-5 w-5 text-emerald-300"/>:<ShieldX className="mb-2 h-5 w-5 text-rose-300"/>}<div className="text-[10px] text-slate-500">PRODUCTION GATE</div><b className={tone(gate?gate.ready:null)}>{gate?(gate.ready?'PASS':'BLOCK'):'ASSESS'}</b></div>
   </section>

   {release?<section className={box(Boolean(assessment))}><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-black">{release.name}</h2><p className="mt-1 text-xs text-slate-500">{release.repository} · <span className="font-mono">{release.candidateSha}</span></p></div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>void act('assess',()=>runAssessmentV34(release.id),'اكتمل V34 Hermetic Assessment.')} className="rounded-xl bg-cyan-300 px-5 py-3 text-xs font-black text-slate-950 disabled:opacity-40">RUN V34 ASSESSMENT</button>{assessment&&<a href={evidenceUrlV34(assessment.id)} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-xs font-black"><Download className="h-4 w-4"/>EVIDENCE ZIP</a>}</div></div>
    {gate&&<div className={`mt-5 rounded-2xl border p-4 ${gate.ready?'border-emerald-400/30 bg-emerald-500/10':'border-rose-400/30 bg-rose-500/10'}`}><div className="font-black">PRODUCTION {gate.ready?'READY':'BLOCKED'}</div><div className="mt-3 grid gap-2 md:grid-cols-2">{gate.blockers.map((x)=><div key={x.code} className="rounded-xl bg-black/20 p-3 text-xs text-rose-200"><b>{x.code}</b><div className="mt-1">{x.message}</div></div>)}{gate.waivedBlockers.map((x)=><div key={x.code} className="rounded-xl bg-black/20 p-3 text-xs text-amber-200"><b>WAIVED · {x.code}</b><div className="mt-1">{x.message}</div></div>)}{gate.warnings.map((x,i)=><div key={i} className="rounded-xl bg-black/20 p-3 text-xs text-amber-200">⚠ {x}</div>)}</div></div>}
   </section>:<section className={box(false)}><AlertTriangle className="mb-3 h-6 w-6 text-amber-300"/><b>لا توجد V31 Release نشطة.</b></section>}

   {assessment&&<section className="grid gap-5 xl:grid-cols-3">
    <div className={box(Boolean(py.hashComplete))}><h2 className="font-black">PYTHON HERMETIC LOCK</h2><div className="mt-4 space-y-2 text-xs"><div className="rounded-xl bg-black/20 p-3">Packages <b className="float-left">{py.packages??0}</b></div><div className="rounded-xl bg-black/20 p-3">SHA-256 hashes <b className="float-left">{py.hashes??0}</b></div><div className="rounded-xl bg-black/20 p-3">Hash complete <b className={`float-left ${py.hashComplete?'text-emerald-300':'text-rose-300'}`}>{py.hashComplete?'YES':'NO'}</b></div><div className="rounded-xl bg-black/20 p-3">torch <b className="float-left">{py.torchVersion||'—'}</b></div><div className="rounded-xl bg-black/20 p-3">torchaudio <b className="float-left">{py.torchaudioVersion||'—'}</b></div></div><div className="mt-3 break-all rounded-xl border border-white/10 p-3 font-mono text-[10px] text-slate-500">{py.sha256||'—'}</div></div>
    <div className={box(Boolean(wf.success))}><h2 className="font-black">HERMETIC WORKFLOW</h2><div className="mt-4 space-y-2 text-xs"><div className="rounded-xl bg-black/20 p-3">Ubuntu 22 ↔ 24 <b className="float-left">{wf.crossRunner?'MATCH':'UNKNOWN'}</b></div><div className="rounded-xl bg-black/20 p-3">Syft <b className="float-left">{wf.syft?'PASS':'UNKNOWN'}</b></div><div className="rounded-xl bg-black/20 p-3">Trivy report <b className="float-left">{wf.scanner?'PASS':'UNKNOWN'}</b></div><div className="rounded-xl bg-black/20 p-3">CRITICAL gate <b className="float-left">{wf.criticalGate?'PASS':'BLOCK'}</b></div><div className="rounded-xl bg-black/20 p-3">OIDC provenance <b className="float-left">{wf.oidc?'PASS':'UNKNOWN'}</b></div></div>{wf.runUrl&&<a href={wf.runUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded-xl border border-white/10 px-3 py-2 text-xs font-black text-cyan-300">OPEN GITHUB RUN</a>}</div>
    <div className={box(Boolean(gh.verifiedPresence))}><h2 className="font-black">GITHUB ATTESTATION API</h2><div className="mt-4 rounded-xl bg-black/20 p-3 text-xs">API available <b className="float-left">{gh.available?'YES':'UNKNOWN'}</b></div><div className="mt-2 rounded-xl bg-black/20 p-3 text-xs">Attestation found <b className={`float-left ${gh.verifiedPresence?'text-emerald-300':'text-amber-300'}`}>{gh.verifiedPresence?'YES':'NOT CONFIRMED'}</b></div><div className="mt-2 rounded-xl bg-black/20 p-3 text-xs">Count <b className="float-left">{gh.count??0}</b></div><div className="mt-3 break-all rounded-xl border border-white/10 p-3 font-mono text-[10px] text-slate-500">{gh.subjectDigest||wf.artifact?.canonicalSha256||'—'}</div></div>
   </section>}

   <section className="grid gap-5 xl:grid-cols-2">
    <div className={box(true)}><div className="flex items-center justify-between"><div><h2 className="font-black">TEMPORARY WAIVERS</h2><p className="mt-1 text-xs text-slate-500">Waiver مرتبطة بنفس Release + Candidate SHA وتنتهي تلقائيًا. Integrity blockers غير قابلة للتجاوز.</p></div></div>{gate?.blockers?.length?<div className="mt-4 grid gap-3"><select value={waiver.code} onChange={e=>setWaiver({...waiver,code:e.target.value})} className="rounded-xl border border-white/10 bg-[#0b1220] px-3 py-2 text-xs"><option value="">اختر Blocker</option>{gate.blockers.filter(x=>!o.nonWaivable.includes(x.code)).map(x=><option key={x.code} value={x.code}>{x.code}</option>)}</select><input value={waiver.reason} onChange={e=>setWaiver({...waiver,reason:e.target.value})} placeholder="سبب الاستثناء المؤقت" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-xs"/><input type="number" min={1} max={Number(policy.waiverMaxHours||168)} value={waiver.hours} onChange={e=>setWaiver({...waiver,hours:Number(e.target.value)})} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-xs"/><button disabled={!waiver.code||waiver.reason.length<12||!!busy} onClick={()=>void act('waiver',()=>createWaiverV34({releaseId:release?.id,blockerCode:waiver.code,reason:waiver.reason,hours:waiver.hours}),'تم إنشاء Waiver مؤقتة.')} className="rounded-xl bg-amber-300 px-4 py-2 text-xs font-black text-slate-950 disabled:opacity-40">CREATE TEMPORARY WAIVER</button></div>:<p className="mt-4 text-xs text-slate-500">لا توجد Blockers قابلة للاستثناء حاليًا.</p>}
     <div className="mt-4 space-y-2">{o.waivers.slice(0,10).map((w:any)=><div key={w.id} className="rounded-xl border border-white/10 p-3 text-xs"><b>{w.blockerCode}</b><span className="float-left text-slate-500">expires {when(w.expiresAt)}</span><div className="mt-1 text-slate-400">{w.reason}</div>{!w.revokedAt&&<button onClick={()=>void act('revoke',()=>revokeWaiverV34(w.id),'تم إلغاء Waiver.')} className="mt-2 rounded-lg border border-rose-400/20 px-2 py-1 text-[10px] text-rose-300">REVOKE</button>}</div>)}</div>
    </div>
    <div className={box(Boolean(v33.ready))}><h2 className="font-black">CHAIN OF TRUST</h2><div className="mt-4 space-y-2 text-xs"><div className="rounded-xl bg-black/20 p-3">V33 Production Gate <b className={`float-left ${v33.ready?'text-emerald-300':'text-rose-300'}`}>{v33.ready?'PASS':'BLOCK'}</b></div><div className="rounded-xl bg-black/20 p-3">Canonical Artifact <b className="float-left">{wf.artifact?.available?'FOUND':'UNKNOWN'}</b></div><div className="rounded-xl bg-black/20 p-3">Scanner threshold <b className="float-left">{wf.scannerThreshold||'—'}</b></div></div><div className="mt-4 flex gap-2"><a href="#video-v33" className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">OPEN V33</a><a href="#video-v32" className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">OPEN V32</a></div></div>
   </section>

   <section className={box(true)}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">V34 PRODUCTION POLICY</h2><p className="mt-1 text-xs text-slate-500">سياسة Gate تُعاد قراءتها لحظة Promotion.</p></div><button disabled={!!busy} onClick={()=>void act('policy',()=>savePolicyV34(policy),'تم حفظ سياسة V34.')} className="rounded-xl bg-cyan-300 px-4 py-2 text-xs font-black text-slate-950">SAVE POLICY</button></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{flags.map(([k,l])=><label key={k} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 p-3 text-xs"><span>{l}</span><input type="checkbox" checked={Boolean(policy[k])} onChange={e=>setPolicy({...policy,[k]:e.target.checked})}/></label>)}</div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs text-slate-500">Evidence max age<input type="number" value={Number(policy.maxEvidenceAgeMinutes||120)} onChange={e=>setPolicy({...policy,maxEvidenceAgeMinutes:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-slate-100"/></label><label className="text-xs text-slate-500">Waiver max hours<input type="number" value={Number(policy.waiverMaxHours||168)} onChange={e=>setPolicy({...policy,waiverMaxHours:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-slate-100"/></label></div></section>
  </div>
 </main>
}
