import { useEffect, useMemo, useState } from 'react'
import { BadgeCheck, Copy, FolderKey, KeyRound, Loader2, RefreshCcw, ShieldCheck, Trash2, UserPlus, Users } from 'lucide-react'
import {
  addAclV23, adminOverviewV23, createInviteV23, createTeamV23, deleteAclV23, deleteTeamV23,
  enterpriseStatusV23, setOwnerV23, setUserActiveV23, setUserRoleV23, V23Acl, V23Permission,
  V23Resource, V23Role, V23Team, V23User,
} from './lib/enterpriseIdentityApi'

type Overview = Awaited<ReturnType<typeof adminOverviewV23>>

export default function VideoStudioV23() {
  const [overview,setOverview]=useState<Overview|null>(null)
  const [busy,setBusy]=useState<string|null>('load')
  const [error,setError]=useState<string|null>(null)
  const [invite,setInvite]=useState({name:'',email:'',role:'reviewer' as V23Role})
  const [shareLink,setShareLink]=useState<string|null>(null)
  const [teamName,setTeamName]=useState('')
  const [teamMembers,setTeamMembers]=useState<string[]>([])
  const [resourceKey,setResourceKey]=useState('')
  const [principalType,setPrincipalType]=useState<'user'|'team'>('user')
  const [principalId,setPrincipalId]=useState('')
  const [permission,setPermission]=useState<V23Permission>('view')
  const [ownerId,setOwnerId]=useState('')

  const refresh=async()=>{setError(null);try{setOverview(await adminOverviewV23())}catch(e){setError(e instanceof Error?e.message:'تعذر فتح Creator V23.')}finally{setBusy(null)}}
  useEffect(()=>{enterpriseStatusV23().catch(()=>undefined);refresh().catch(()=>undefined)},[])

  const users=overview?.users||[]
  const teams=overview?.teams||[]
  const resources=overview?.resources||[]
  const acl=overview?.acl||[]
  const selectedResource=useMemo(()=>resources.find(r=>`${r.type}:${r.id}`===resourceKey)||null,[resources,resourceKey])

  const run=async(id:string,fn:()=>Promise<unknown>)=>{setBusy(id);setError(null);try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية.')}finally{setBusy(null)}}
  const createInvite=async()=>{setBusy('invite');setError(null);try{const result=await createInviteV23(invite);setShareLink(`${window.location.origin}${window.location.pathname}${result.shareFragment}`);setInvite({name:'',email:'',role:'reviewer'});await refresh()}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الدعوة.')}finally{setBusy(null)}}
  const createTeam=()=>run('team',async()=>{await createTeamV23(teamName,teamMembers);setTeamName('');setTeamMembers([])})
  const grant=()=>run('acl',async()=>{if(!selectedResource||!principalId)return;await addAclV23({resourceType:selectedResource.type,resourceId:selectedResource.id,principalType,principalId,permission})})
  const setOwner=()=>run('owner',async()=>{if(!selectedResource||!ownerId)return;await setOwnerV23(selectedResource.type,selectedResource.id,ownerId)})

  if(busy==='load'&&!overview)return <main className="grid min-h-screen place-items-center bg-[#05080d]"><Loader2 className="h-8 w-8 animate-spin text-cyan-300"/></main>

  return <main className="min-h-screen bg-[#05080d] text-slate-100" dir="rtl">
    <header className="border-b border-white/8 bg-[#080d15] px-5 py-4"><div className="mx-auto flex max-w-[1750px] flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-cyan-300"/><div><p className="text-[10px] font-black tracking-[.3em] text-cyan-300">MAGHRABI CREATOR V23</p><h1 className="text-xl font-black">Identity & Enterprise Collaboration</h1></div></div><div className="flex gap-2"><a href="#team" className="rounded-xl border border-cyan-300/30 px-4 py-2 text-xs font-black text-cyan-200">TEAM WORKSPACE</a><a href="#video-v22" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black text-slate-300">V22 REVIEW</a><button onClick={()=>refresh()} className="rounded-xl border border-white/10 px-3 py-2 text-xs"><RefreshCcw className="ml-1 inline h-4 w-4"/>REFRESH</button></div></div></header>
    <div className="mx-auto grid max-w-[1750px] gap-4 p-4 xl:grid-cols-[360px_minmax(0,1fr)_390px]">
      <aside className="space-y-4">
        <section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><div className="flex items-center gap-2"><UserPlus className="h-4 w-4 text-cyan-300"/><h2 className="text-xs font-black">INVITE USER</h2></div><input value={invite.name} onChange={e=>setInvite(v=>({...v,name:e.target.value}))} placeholder="الاسم" className="mt-3 w-full rounded-xl border border-white/8 bg-black/30 p-2.5 text-xs"/><input value={invite.email} onChange={e=>setInvite(v=>({...v,email:e.target.value}))} placeholder="email@example.com" className="mt-2 w-full rounded-xl border border-white/8 bg-black/30 p-2.5 text-xs"/><select value={invite.role} onChange={e=>setInvite(v=>({...v,role:e.target.value as V23Role}))} className="mt-2 w-full rounded-xl border border-white/8 bg-black/30 p-2.5 text-xs">{['admin','producer','editor','reviewer','viewer'].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy==='invite'||!invite.name||!invite.email} onClick={createInvite} className="mt-3 w-full rounded-xl bg-cyan-300 p-2.5 text-xs font-black text-slate-950">CREATE INVITE LINK</button>{shareLink&&<div className="mt-3 rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-3 text-[9px] text-emerald-200"><p className="break-all">{shareLink}</p><button onClick={()=>navigator.clipboard.writeText(shareLink)} className="mt-2 rounded-lg border border-emerald-300/20 px-3 py-1.5"><Copy className="ml-1 inline h-3 w-3"/>COPY</button></div>}</section>
        <section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-fuchsia-300"/><h2 className="text-xs font-black">CREATE TEAM</h2></div><input value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="اسم الفريق" className="mt-3 w-full rounded-xl border border-white/8 bg-black/30 p-2.5 text-xs"/><div className="mt-3 max-h-44 space-y-1 overflow-auto">{users.filter(u=>u.active).map(u=><label key={u.id} className="flex items-center gap-2 rounded-lg bg-black/20 p-2 text-[10px]"><input type="checkbox" checked={teamMembers.includes(u.id)} onChange={e=>setTeamMembers(v=>e.target.checked?[...v,u.id]:v.filter(x=>x!==u.id))}/><span className="flex-1">{u.name}</span><span className="text-slate-600">{u.role}</span></label>)}</div><button disabled={!teamName||busy==='team'} onClick={createTeam} className="mt-3 w-full rounded-xl border border-fuchsia-300/30 p-2.5 text-xs font-black text-fuchsia-200">CREATE TEAM</button></section>
      </aside>

      <section className="space-y-4">
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="USERS" value={users.length}/><Metric label="ACTIVE" value={users.filter(u=>u.active).length}/><Metric label="TEAMS" value={teams.length}/><Metric label="ACL RULES" value={acl.length}/></div>
        <section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><div className="flex items-center gap-2"><BadgeCheck className="h-4 w-4 text-cyan-300"/><h2 className="text-xs font-black">USERS & ROLES</h2></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[700px] text-right text-[10px]"><thead className="text-slate-600"><tr><th className="p-2">USER</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>LAST LOGIN</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="p-2 font-black">{u.name}</td><td className="text-slate-500">{u.email}</td><td><select value={u.role} onChange={e=>run(`role-${u.id}`,()=>setUserRoleV23(u.id,e.target.value as V23Role))} className="rounded-lg bg-black/30 p-1.5">{['admin','producer','editor','reviewer','viewer'].map(r=><option key={r}>{r}</option>)}</select></td><td><button onClick={()=>run(`active-${u.id}`,()=>setUserActiveV23(u.id,!u.active))} className={`rounded-lg px-2 py-1 ${u.active?'bg-emerald-300/10 text-emerald-300':'bg-rose-300/10 text-rose-300'}`}>{u.active?'ACTIVE':'DISABLED'}</button></td><td className="text-slate-600">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString('ar-SA'):'—'}</td></tr>)}</tbody></table></div></section>
        <section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><div className="flex items-center gap-2"><FolderKey className="h-4 w-4 text-amber-300"/><h2 className="text-xs font-black">PROJECT ACL & OWNERSHIP</h2></div><div className="mt-3 grid gap-2 md:grid-cols-2"><select value={resourceKey} onChange={e=>setResourceKey(e.target.value)} className="rounded-xl bg-black/30 p-2.5 text-xs"><option value="">اختر المشروع / Review Room</option>{resources.map(r=><option key={`${r.type}:${r.id}`} value={`${r.type}:${r.id}`}>{r.type==='v22_room'?'REVIEW':'PROJECT'} · {r.name}</option>)}</select><select value={principalType} onChange={e=>{setPrincipalType(e.target.value as 'user'|'team');setPrincipalId('')}} className="rounded-xl bg-black/30 p-2.5 text-xs"><option value="user">USER</option><option value="team">TEAM</option></select><select value={principalId} onChange={e=>setPrincipalId(e.target.value)} className="rounded-xl bg-black/30 p-2.5 text-xs"><option value="">اختر المستفيد</option>{(principalType==='user'?users:teams).map((x:V23User|V23Team)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={permission} onChange={e=>setPermission(e.target.value as V23Permission)} className="rounded-xl bg-black/30 p-2.5 text-xs">{['view','review','edit','manage'].map(p=><option key={p}>{p}</option>)}</select></div><button disabled={!selectedResource||!principalId} onClick={grant} className="mt-2 rounded-xl bg-amber-300 px-4 py-2 text-xs font-black text-slate-950">GRANT ACCESS</button><div className="mt-4 flex gap-2"><select value={ownerId} onChange={e=>setOwnerId(e.target.value)} className="flex-1 rounded-xl bg-black/30 p-2.5 text-xs"><option value="">اختر Owner</option>{users.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button disabled={!selectedResource||!ownerId} onClick={setOwner} className="rounded-xl border border-cyan-300/30 px-4 text-xs font-black text-cyan-200">SET OWNER</button></div><div className="mt-4 max-h-60 space-y-2 overflow-auto">{acl.map(a=><div key={a.id} className="flex items-center gap-2 rounded-xl border border-white/6 bg-black/20 p-2 text-[9px]"><span className="flex-1">{a.resourceType} · {a.resourceId.slice(0,8)} · {a.principalType}:{a.principalId.slice(0,8)} · <b className="text-cyan-300">{a.permission}</b>{a.ownerUserId?' · OWNER':''}</span><button onClick={()=>run(`acl-${a.id}`,()=>deleteAclV23(a.id))} className="text-rose-300"><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div></section>
      </section>

      <aside className="space-y-4"><section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><h2 className="text-xs font-black">TEAMS · {teams.length}</h2><div className="mt-3 space-y-2">{teams.map(t=><div key={t.id} className="rounded-xl border border-white/7 bg-black/20 p-3"><div className="flex items-center justify-between"><b className="text-[11px]">{t.name}</b><button onClick={()=>run(`delteam-${t.id}`,()=>deleteTeamV23(t.id))} className="text-rose-300"><Trash2 className="h-3.5 w-3.5"/></button></div><p className="mt-1 text-[9px] text-slate-600">{t.memberIds.length} members</p></div>)}</div></section><section className="rounded-3xl border border-white/8 bg-[#0a1019] p-4"><h2 className="text-xs font-black">AUDIT LOG</h2><div className="mt-3 max-h-[620px] space-y-2 overflow-auto">{overview?.audit.map(a=><div key={a.id} className="rounded-xl border border-white/6 bg-black/20 p-3"><div className="flex justify-between gap-2 text-[9px]"><b className="text-cyan-300">{a.action}</b><span className="text-slate-600">{new Date(a.createdAt).toLocaleString('ar-SA')}</span></div><p className="mt-1 text-[9px] text-slate-400">{a.actorName} · {a.actorRole}</p></div>)}</div></section>{error&&<div className="rounded-xl border border-rose-300/20 bg-rose-300/5 p-3 text-xs text-rose-200">{error}</div>}</aside>
    </div>
  </main>
}

function Metric({label,value}:{label:string;value:number}) { return <div className="rounded-2xl border border-white/7 bg-[#0a1019] p-3"><p className="text-[8px] font-black tracking-[.2em] text-slate-600">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div> }
